### PR TITLE
Fix #139, compiler warnings on mcp750 PSP

### LINKED ISSUE #139: MCP750 PSP fails to build
**Describe the bug**

Building the current "master" branch for mcp750 yields the following build error:
```
/home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_memory.c: In function 'CFE_PSP_GetCFETextSegmentInfo':
/home/jphickey/cfecfs/github/psp/fsw/mcp750-vxworks/src/cfe_psp_memory.c:426: error: passing argument 1 of 'moduleFindByName' discards qualifiers from pointer target type
```

**To Reproduce**
Build "master" using standard procedure and default config.

**Expected behavior**
Build should succeed.

**System observed on:**
 - GSFC MCP750 build machine (gs582w-cfelnx)

**Additional context**
This is an error now due to the inclusion of `-Wall -Werror` in the default build.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**

Fix #139

Patches for the MCP750 PSP to avoid some compiler warnings that show up when building with strict flags.

**Testing performed**
Build for MCP750 using default config and procedure, confirm warnings are fixed (others still exist in other modules, however).

**Expected behavior changes**
No impact to behavior.  Only fixes warnings.

**System(s) tested on**
 - GSFC build host (gs582w-cfelnx)

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

File: fsw/mcp750-vxworks/src/cfe_psp_memory.c [hunk 1]
```diff
@@ -59,7 +59,9 @@
 /*
 ** Define the cFE Core loadable module name
 */
-#define CFE_MODULE_NAME "cfe-core.o"
+#define CFE_MODULE_NAME_DEFAULT "cfe-core.o"
```
Comment (skliper) [inline fsw/mcp750-vxworks/src/cfe_psp_memory.c]: Would it make sense to relate this to the build definition vs redefining here, or maybe an #ifndef?  Feels like a duplicate definition which could be single sourced (see EXE_TARGET).

Comment (jphickey) [reply fsw/mcp750-vxworks/src/cfe_psp_memory.c]: Yes, but I did notice that there is a separate issue about that (see #111) and so I figured it would be better to keep this pull request isolated to this specific warning, then fix the hardcoded definition of `cfe-core.o` in a pull request associated with the other ticket.

**Comment by astrogeco** [comment]
CCB 20200311 - Approved
