### PR TITLE
Fix #382, Replace exit(1) and exit(-1) with EXIT_FAILURE macro

### LINKED ISSUE #382: Replace exit(1) and exit(-1) with preferred macro EXIT_FAILURE
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the bug**
PSP contains a few uses of `exit(1)` and 'exit(-1)'.
Copy of https://github.com/nasa/tblCRCTool/pull/77

**Expected behavior**
Recommend replacing with the more expressive and more portable `EXIT_FAILURE` or 'EXIT_SUCCESS' macros.

**Code snips**
https://github.com/nasa/PSP/blob/6fceb13c1dc433f0943fb41511acd1f9a96916f3/fsw/mcp750-vxworks/src/cfe_psp_support.c#L118
https://github.com/nasa/PSP/blob/6fceb13c1dc433f0943fb41511acd1f9a96916f3/fsw/pc-rtems/src/cfe_psp_support.c#L84

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #382 
  - A few cases of `exit(1)` and `exit(-1)` replaced with `EXIT_FAILURE` macro.

Note: A single case was replaced with `EXIT_SUCCESS` in `CFE_PSP_DisplayUsage()` - this call to `exit()` seems to be there simply to explicitly end execution of the function (it's a `void` function) so I assume there is no difference between exiting with SUCCESS or FAILURE.

**Testing performed**
GitHub CI actions all passing successfully.
Tested locally to confirm no change to test outcomes or coverage.

**Expected behavior changes**
No change to behavior.
The macros are more expressive and potentially more portable.

**System(s) tested on**
Intel(R) Celeron(R) N4100 CPU @ 1.10GHz x86_64
Debian GNU/Linux 11 (bullseye)
Current main branch of cFS.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

**Review by skliper — APPROVED** [review]

File: fsw/pc-linux/src/cfe_psp_start.c [hunk 1]
```diff
@@ -531,7 +531,7 @@ void CFE_PSP_DisplayUsage(char *Name)
     printf("       %s --reset PO --subtype 1 --cpuid 1 --cpuname CPU1 --scid 32\n", Name);
     printf(" \n");
 
-    exit(1);
+    exit(EXIT_SUCCESS);
```
Comment (jphickey) [inline fsw/pc-linux/src/cfe_psp_start.c:534]: Not sure about this - the old `exit(1)` is an error/fail code, because traditionally `exit(0)` is success on UNIX.  This should probably be `exit(EXIT_FAILURE)` to maintain this - and usually running with bad options should be a failure, not a success.

**Review by jphickey — CHANGES_REQUESTED** [review]
Minor request

File: fsw/pc-linux/src/cfe_psp_start.c (hunk 1 above)
Comment (thnkslprpt) [reply fsw/pc-linux/src/cfe_psp_start.c:534]: No worries Joe.
Updated.

**Review by jphickey — APPROVED** [review]

File: fsw/mcp750-vxworks/src/cfe_psp_support.c [hunk 2]
```diff
@@ -115,7 +115,7 @@ void CFE_PSP_Restart(uint32 reset_type)
 void CFE_PSP_Panic(int32 ErrorCode)
 {
     printf("CFE_PSP_Panic Called with error code = 0x%08X. Exiting.\n", (unsigned int)ErrorCode);
-    exit(-1); /* Need to improve this */
+    exit(EXIT_FAILURE); /* Need to improve this */
```
Comment (skliper) [inline fsw/mcp750-vxworks/src/cfe_psp_support.c:118]: Recommend removing comment and rebasing.  Then should be good to go.

NOTE: If anyone knows what improvement this was referring to I suggest writing an issue.  Linux aborts to get a core file, RTEMS just exits.

Comment (thnkslprpt) [reply fsw/mcp750-vxworks/src/cfe_psp_support.c]: Jake @skliper - Rebased to main and removed the comment.
Cheers

**Review by skliper — APPROVED** [review]

**Comment by skliper** [comment]
@dzbaker Recommending CCB review/merge
