### PR TITLE
Fix #440 - rename parameter in CFE_PSP_MemSet handler to align with stub and actual code

### LINKED ISSUE #440: CFE_PSP_MemSet stub and handler parameter mis-match
**Describe the bug**
The handler for CFE_PSP_MemSet expects a parameter named "size", whereas the stub defines the third parameter as named "n".

**To Reproduce**
Calling the CFE_PSP_MemSet stub results in: `[ FAIL] 18.011 utstubs.c:868 - Requested parameter size of size 4 which was not provided by the stub`

**Expected behavior**
Calling the default stub/handler should behave normally.

**Code snips**
See https://github.com/nasa/PSP/blob/ab82f6a2336da125ba4cff2a10862869f7016fab/ut-stubs/src/cfe_psp_memaccess_api_handlers.c#L48

and

https://github.com/nasa/PSP/blob/main/ut-stubs/src/cfe_psp_memaccess_api_stubs.c#L108

**System observed on:**
Ubuntu 24

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

### PR DESCRIPTION
**Pull request by CDKnightNASA**
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/PSP/blob/main/CONTRIBUTING.md).
* [X] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
Addresses a mis-match with the parameter name in the CFE_PSP_MemSet handler and stub.

**Testing performed**
Built cFS with change, including coverage test that uncovered this issue.

**Expected behavior changes**
 - Behavior Change: Correct handler behavior.

**System(s) tested on**
Oracle Linux 8

**Contributor Info - All information REQUIRED for consideration of pull request**
Christopher.D.Knight@nasa.gov

### CODE REVIEW

**Review by RichLandau — APPROVED** [review]

**Comment by CDKnightNASA** [comment]
also fixed CFE_PSP_MemCpy

File: ut-stubs/src/cfe_psp_memaccess_api_handlers.c [hunk 1]
```diff
@@ -45,7 +45,7 @@ void UT_DefaultHandler_CFE_PSP_MemCpy(void *UserObj, UT_EntryKey_t FuncKey, cons
     /* CFE_PSP_MemCpy(void *dest, const void *src, uint32 size) */
     void *      dest = UT_Hook_GetArgValueByName(Context, "dest", void *);
     const void *src  = UT_Hook_GetArgValueByName(Context, "src", const void *);
-    uint32      size = UT_Hook_GetArgValueByName(Context, "size", uint32);
+    uint32      n    = UT_Hook_GetArgValueByName(Context, "n", uint32);
```
Comment (dzbaker) [inline ut-stubs/src/cfe_psp_memaccess_api_handlers.c:48]: Renamed variable was not updated in memcpy() on line 54. I've corrected this in commit e0fd658ebcff4491a203e0a5fb01dd05992aceb0.
