### PR TITLE
Fix #443, Correct minor bugs + typos in the VxWorks layer

### LINKED ISSUE #443: MCP750/VxWorks typos + minor bugs
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
There area  few typos and minor bugs in the VxWorks PSP layer.
e.g. reset-type/sub-type:
https://github.com/nasa/PSP/blob/cdc73e5f6564f678207bec69cb75d456795ce91c/fsw/mcp750-vxworks/src/cfe_psp_start.c#L163-L179

GetModuldIdFunc missing the 'e' in 'Module:
https://github.com/nasa/PSP/blob/cdc73e5f6564f678207bec69cb75d456795ce91c/fsw/mcp750-vxworks/src/cfe_psp_memory.c#L474-L481

**Expected behavior**
Correct for clarity-sake.

**Reporter Info**
Avi Weiss &nbsp; @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #443 
  - Correct typos
  - Remove redundant return variable in `CFE_PSP_InitProcessorReservedMemory` (always returns `CFE_PSP_SUCCESS` anyway)
  - Correct type/sub-type in one of the cases in `OS_Application_Startup`

**Testing performed**
GitHub CI actions all passing successfully and confirmed locally that test coverage is unaffected.

**Expected behavior changes**
Logic unchanged other than fixes mentioned above.

**System(s) tested on**
Debian 12 using the current main branch of cFS bundle.

**Contributor Info**
Avi Weiss &nbsp; @thnkslprpt

### CODE REVIEW

File: fsw/mcp750-vxworks/src/cfe_psp_memory.c [hunk 1]
```diff
@@ -319,9 +319,7 @@ int32 CFE_PSP_GetVolatileDiskMem(cpuaddr *PtrToVolDisk, uint32 *SizeOfVolDisk)
 */
 int32 CFE_PSP_InitProcessorReservedMemory(uint32 RestartType)
 {
-    int32 return_code;
-
-    if (RestartType != CFE_PSP_RST_TYPE_PROCESSOR)
+    if (RestartType == CFE_PSP_RST_TYPE_POWERON)
```
Comment (dzbaker) [inline fsw/mcp750-vxworks/src/cfe_psp_memory.c:322]: Hi @thnkslprpt, what was the rationale for changing this to check for equaling POWERON?

File: fsw/mcp750-vxworks/src/cfe_psp_start.c [hunk 2]
```diff
@@ -169,8 +169,8 @@ void OS_Application_Startup(void)
     else if (reset_register & SYS_REG_BLRR_FBTN)
     {
         OS_printf("CFE_PSP: POWERON Reset: Front Panel Push Button Reset.\n");
-        reset_type    = CFE_PSP_RST_SUBTYPE_PUSH_BUTTON;
-        reset_subtype = 3;
+        reset_type    = CFE_PSP_RST_TYPE_POWERON;
+        reset_subtype = CFE_PSP_RST_SUBTYPE_PUSH_BUTTON;
```
Comment (dzbaker) [inline fsw/mcp750-vxworks/src/cfe_psp_start.c:173]: To discuss at CCB: This changes the subtype from 3 to 2.

**Comment by dzbaker** [comment]
CCB 10 April 2025: Decided to wait for response from @thnkslprpt and then approve.
